# Generated by Django 5.2.7 on 2025-10-16 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0002_alter_user_password_tip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField()),
                ('tip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex.tip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ex.user')),
            ],
        ),
    ]
