# Generated by Django 5.2.7 on 2025-10-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0004_alter_vote_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='downvoted_by',
            field=models.ManyToManyField(blank=True, related_name='downvoted_tips', to='ex.user'),
        ),
        migrations.AddField(
            model_name='tip',
            name='upvoted_by',
            field=models.ManyToManyField(blank=True, related_name='upvoted_tips', to='ex.user'),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
