# Generated by Django 5.2.7 on 2025-10-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0005_tip_downvoted_by_tip_upvoted_by_delete_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_delete_tips',
            field=models.BooleanField(default=False),
        ),
    ]
