# Generated by Django 5.2.7 on 2025-10-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0006_user_can_delete_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_downvote_tips',
            field=models.BooleanField(default=False),
        ),
    ]
