# Generated by Django 5.2.7 on 2025-10-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0007_user_can_downvote_tips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='can_delete_tips',
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_downvote_tips',
        ),
    ]
