# Generated by Django 5.2.7 on 2025-10-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0008_remove_user_can_delete_tips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_downvote_tips',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='has_right_to_delete_tips',
            field=models.BooleanField(default=False),
        ),
    ]
