# Generated by Django 5.2.7 on 2025-10-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ex', '0009_user_can_downvote_tips_user_has_right_to_delete_tips'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tip',
            options={'permissions': [('can_downvote_tips', 'Can downvote tips')]},
        ),
        migrations.RemoveField(
            model_name='user',
            name='can_downvote_tips',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_right_to_delete_tips',
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
