# Generated by Django 5.2.7 on 2025-10-19 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex00', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name='userfavoritearticle',
                    name='article',
                ),
                migrations.RemoveField(
                    model_name='userfavoritearticle',
                    name='user',
                ),
                migrations.DeleteModel(
                    name='Article',
                ),
                migrations.DeleteModel(
                    name='UserFavoriteArticle',
                ),
            ],
            database_operations=[],
        ),
    ]
