# Generated by Django 5.2.7 on 2025-10-19 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ex00', '0002_remove_userfavoritearticle_article_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Article',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('title', models.CharField(max_length=64)),
                        ('created', models.DateTimeField(auto_now_add=True)),
                        ('synopsis', models.CharField(max_length=312)),
                        ('content', models.TextField()),
                        ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'ex00_article',
                    },
                ),
                migrations.CreateModel(
                    name='UserFavoriteArticle',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article')),
                        ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'ex00_userfavoritearticle',
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
